Module12 task1
htmlacademy-javascript/1052685-keksobooking-24 pull request #10
Opened 2021-11-07 17:10 UTC by nelmare

2021-11-08 10:33 UTC, balesniy requested changes
код в порядке, осталось по доп критериям пробежаться

2021-11-08 10:33 UTC, balesniy commented on js/ad-form.js
> +  TWO: 5000,
можно найти более наглядные названия, например FLAT

2021-11-08 10:33 UTC, balesniy commented on js/ad-form.js
> +    minPrice: [MinPrice.NULL],
поле minPrice повторяется, выглядит избыточным, и массив для значений тоже

2021-11-08 10:33 UTC, balesniy commented on js/ad-form.js
> +adHouseType.addEventListener('input', onHousingTypeChangeMinPrice);
если схема именования обработчика "элемент+событие", то тут не change а input

2021-11-08 10:33 UTC, balesniy commented on js/api.js
> +        onSuccessMessageShow();
- вызов onSuccessMessageShow лучше перенести в колбек onSuccess, чтобы не нагружать модуль api
- onErrorMessageShow также

2021-11-08 10:33 UTC, balesniy commented on js/form-filter-clear.js
> +    featuresFilterInput.checked = false;
у формы есть метод reset который сбрасывает значения до указанных в разметке

2021-11-08 10:33 UTC, balesniy commented on js/form-filter-clear.js
> +  onSubmitClearData();
такое название подходит для обработчика, который мы передаем колбэком, для обычной функции нужен глагол, отражающий действие, например clearForm

2021-11-08 10:33 UTC, balesniy commented on js/form-submit-message.js
> +    evt.preventDefault();
можно упростить код - вынести проверку isEscapeKey и убрать evt.preventDefault

2021-11-08 10:33 UTC, balesniy commented on js/map.js
> +  const isHousingTypeOptionSelected = (ad) => housingTypeFilter.value === ANY_VALUE || housingTypeFilter.value === ad.offer.type;
функции проверок отдельного объявления можно вынести из onGetDataSuccess

2021-11-08 10:33 UTC, balesniy commented on js/preview.js
> +  const matches = FILE_TYPES.some((item) => fileName.endsWith(item));
повторяется код в обработчиках, можно вынести в отдельную функцию

2021-11-08 20:56 UTC, nelmare commented on js/map.js
> +  const isHousingTypeOptionSelected = (ad) => housingTypeFilter.value === ANY_VALUE || housingTypeFilter.value === ad.offer.type;
почему так нужно делать?

2021-11-09 18:56 UTC, balesniy approved these changes

2021-11-09 18:56 UTC, merged