Отрисуй меня полностью (часть 1)
htmlacademy-javascript/1052685-keksobooking-24 pull request #5
Opened 2021-10-16 17:34 UTC by nelmare

2021-10-17 14:09 UTC, balesniy requested changes
- обрати внимание на нейминг, он у нас в базовых критериях

2021-10-17 14:09 UTC, balesniy commented on js/popup.js
> +  switch (item.offer.type) {
в простом случае вроде этого, когда код в ветках не отличается, вместо switch можно использовать объект-словарь, вида `const type = {'flat': 'квартира'}`, тогда можно будет одной строкой записать `adItem.querySelector('.popup__type').textContent = type[item.offer.type];`, если оставлять switch, то нужно вынести типы в константы и поиск по селектору вынести из веток.

2021-10-17 14:09 UTC, balesniy commented on js/popup.js
> +  adItem.querySelector('.popup__features').textContent = item.offer.features ? item.offer.features.join(', ') : '';
с этим блоком сложнее, нам нужно вывести иконки popup__features, для этого перебрать массив offer.features, создать отдельные элементы и добавить им классы как в образце.

2021-10-17 14:09 UTC, balesniy commented on js/popup.js
> +  adItem.querySelector('.popup__photos').textContent = item.offer.photos ? item.offer.photos.join(', ') : '';
"Каждая из строк массива photos должна записываться как атрибут src соответствующего изображения." - тут тоже цикл по массиву и для каждого элемента свое изображение

2021-10-18 17:11 UTC, nelmare commented on js/util.js
> +const declOfNum = (n, textForms) => {
Поняла, поторопилась

2021-10-20 08:36 UTC, balesniy approved these changes

2021-10-20 08:36 UTC, balesniy commented on js/data.js
> +  const orderNum = (i < 10 ? '0' : '') + i;
https://up.htmlacademy.ru/javascript/24/criteries#b4 "Сокращения в словах запрещены."

2021-10-20 08:36 UTC, balesniy commented on js/data.js
> +export {data};
экспорты обычно собирают "внизу" файла, после кода, так их потом удобнее искать

2021-10-20 08:36 UTC, merged